### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by widardd** [jwflory/last2libre#8]
exporting from lastfm is running into parsing issues it seems and importing into librefm is stopping after a few thousands scrobbles, too.

Try the user "widardd" on lastfm, page 463 and 464 (of 1673) for example. If I skip both it works again until 470 only to stop again:

`Got page 470 of 1673..
Wrote page 465-470 of 1673 to file export3.json
Traceback (most recent call last):
  File "./lastexport.py", line 204, in <module>
    main(server, username, startpage, outfile, infotype)
  File "./lastexport.py", line 182, in main
    for page, totalpages, tracks in get_tracks(server, username, startpage, tracktype=infotype):
  File "./lastexport.py", line 163, in get_tracks
    tracklist = get_tracklist(response)
  File "./lastexport.py", line 110, in get_tracklist
    xmlpage = ET.fromstring(response)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 45, column 127
`

**Comment by justwheel** [comment]
@widardd Hi, thanks for opening the issue. I have to admit that I don't have much time to work on this nowadays, and I forked it from another project many years ago that also had issues with the Libre.fm API. If you have some programming experience and want to try fixing this, I'm happy to accept a patch. Sorry I can't be of more help.
